#!/bin/sh
./configure \
--prefix=/usr/local/nginx \
--error-log-path=/data/application/logs/nginx/error.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-log-path=/data/application/logs/nginx/access.log \
--with-http_stub_status_module \
--with-http_ssl_module \
--with-http_gzip_static_module \
--with-ipv6 \
--with-http_realip_module \
--with-http_v2_module
make
make install
